# Assembly ECHO dispense
### Takes the postional gRNA information from L+D and dispenses 

<b>Input Files </b>
- The notebook takes positional gRNA units from the destination plate of the L+D 
- Those positional gRNA units are then combined into arrays based on the input file

<b>Output Files </b>
- .csv ECHO dispense sheet for plasmid assemblies of 1-60 
- Always dispenses 1 uL of each linker and vector, 0.5 uL of cutsmart

<b>Notes for new users </b>
- If using more or less than 4 gRNAs, some changes are necessary
- Changes also necessary if the number of gRNA specific locations is greater than 40 (e.g., impinges upon the deadvolume of PP384 ECHO plate)
- Changes necessary if number of arrays of a specific vector are greater than 40 for the same reason aboe
    - May be adjusted by adding another vector step in the ligation + digestion and allocation at here with a "_2" suffix

#### Import libraries and relevant files

In [1]:
import matplotlib.pylab as plt
import chart_studio.plotly as py
import numpy as np
import pandas as pd
import array
import random
import string
import os
from datetime import datetime
from collections import defaultdict

In [2]:
cycle = 5

dispense_path= f"dbtl{cycle}"
timestamp = datetime.now().strftime("%Y%m%d")

In [3]:
filename = f'{timestamp}_ECHO_assemblies_DBTL{cycle}.csv'
data=pd.read_csv(os.path.join(dispense_path,f'{timestamp}_Targets_DBTL{cycle}.csv'))
df=pd.DataFrame(data)
data.head(10)

   number_of_grna   gRNA_1   gRNA_2   gRNA_3   gRNA_4
0               4  PP_0368  PP_0812  PP_0815  PP_2136
1               4  PP_0368  PP_0751  PP_0812  PP_0815
2               4  PP_0751  PP_0812  PP_0813  PP_0815
3               4  PP_0368  PP_0812  PP_0813  PP_0815
4               4  PP_0368  PP_0812  PP_0815  PP_1769
5               3  PP_0751  PP_0814  PP_4189      NaN
6               3  PP_0751  PP_0812  PP_0813      NaN
7               3  PP_0751  PP_0812  PP_0815      NaN
8               3  PP_0368  PP_0528  PP_0812      NaN
9               3  PP_0751  PP_0813  PP_0815      NaN

* Include the vector, then relabel the gRNAs based on their position by fitting the string "_{i}" according to column label

In [4]:
temp_df = df.copy() #useful to avoid iterating when rerunning
temp_df['number_of_grna'] = 'Vector_' + temp_df['number_of_grna'].astype(str)

# Adding suffixes to the gRNA columns
for i in range(1, 5):
    temp_df[f'gRNA_{i}'] = temp_df[f'gRNA_{i}'] + f'_{i}'

temp_df

   number_of_grna     gRNA_1     gRNA_2     gRNA_3     gRNA_4
0        Vector_4  PP_0368_1  PP_0812_2  PP_0815_3  PP_2136_4
1        Vector_4  PP_0368_1  PP_0751_2  PP_0812_3  PP_0815_4
2        Vector_4  PP_0751_1  PP_0812_2  PP_0813_3  PP_0815_4
3        Vector_4  PP_0368_1  PP_0812_2  PP_0813_3  PP_0815_4
4        Vector_4  PP_0368_1  PP_0812_2  PP_0815_3  PP_1769_4
5        Vector_3  PP_0751_1  PP_0814_2  PP_4189_3        NaN
6        Vector_3  PP_0751_1  PP_0812_2  PP_0813_3        NaN
7        Vector_3  PP_0751_1  PP_0812_2  PP_0815_3        NaN
8        Vector_3  PP_0368_1  PP_0528_2  PP_0812_3        NaN
9        Vector_3  PP_0751_1  PP_0813_2  PP_0815_3        NaN
10       Vector_3  PP_0751_1  PP_0814_2  PP_0815_3        NaN
11       Vector_3  PP_0751_1  PP_0812_2  PP_4189_3        NaN
12       Vector_3  PP_0751_1  PP_0815_2  PP_4189_3        NaN
13       Vector_3  PP_0814_1  PP_0815_2  PP_1506_3        NaN
14       Vector_3  PP_0812_1  PP_0815_2  PP_4189_3        NaN
15       Vector_3  PP_0812_1  PP_0815_2  PP_2136_3        NaN
16       Vector_3  PP_0812_1  PP_0814_2  PP_0815_3        NaN
17       Vector_3  PP_0812_1  PP_0813_2  PP_4189_3        NaN
18       Vector_3  PP_0812_1  PP_0813_2  PP_1317_3        NaN
19       Vector_3  PP_0813_1  PP_0814_2  PP_0815_3        NaN
20       Vector_3  PP_0814_1  PP_0815_2  PP_1769_3        NaN
21       Vector_3  PP_0368_1  PP_0813_2  PP_0815_3        NaN
22       Vector_3  PP_0814_1  PP_0815_2  PP_2136_3        NaN
23       Vector_3  PP_0368_1  PP_0751_2  PP_0812_3        NaN
24       Vector_3  PP_0368_1  PP_0751_2  PP_0813_3        NaN
25       Vector_3  PP_0368_1  PP_0751_2  PP_0815_3        NaN
26       Vector_3  PP_0368_1  PP_0751_2  PP_4189_3        NaN
27       Vector_3  PP_0368_1  PP_0812_2  PP_0814_3        NaN
28       Vector_3  PP_0368_1  PP_0812_2  PP_1317_3        NaN
29       Vector_3  PP_0368_1  PP_0812_2  PP_2136_3        NaN
30       Vector_3  PP_0368_1  PP_0812_2  PP_4189_3        NaN
31       Vector_3  PP_0812_1  PP_0813_2  PP_0814_3        NaN
32       Vector_3  PP_0368_1  PP_0813_2  PP_4189_3        NaN
33       Vector_3  PP_0368_1  PP_0814_2  PP_0815_3        NaN
34       Vector_3  PP_0368_1  PP_0815_2  PP_4189_3        NaN
35       Vector_2  PP_0812_1  PP_2136_2        NaN        NaN
36       Vector_2  PP_0815_1  PP_4191_2        NaN        NaN
37       Vector_2  PP_0812_1  PP_4191_2        NaN        NaN
38       Vector_2  PP_0815_1  PP_2136_2        NaN        NaN
39       Vector_2  PP_0813_1  PP_1317_2        NaN        NaN
40       Vector_2  PP_0813_1  PP_2136_2        NaN        NaN
41       Vector_2  PP_0812_1  PP_0813_2        NaN        NaN
42       Vector_2  PP_0368_1  PP_0437_2        NaN        NaN
43       Vector_2  PP_0751_1  PP_4192_2        NaN        NaN
44       Vector_2  PP_0528_1  PP_0813_2        NaN        NaN
45       Vector_2  PP_0437_1  PP_0751_2        NaN        NaN
46       Vector_2  PP_0437_1  PP_0812_2        NaN        NaN
47       Vector_2  PP_0437_1  PP_0813_2        NaN        NaN
48       Vector_2  PP_0437_1  PP_0815_2        NaN        NaN
49       Vector_2  PP_0528_1  PP_0751_2        NaN        NaN
50       Vector_2  PP_0528_1  PP_0812_2        NaN        NaN
51       Vector_2  PP_0528_1  PP_1317_2        NaN        NaN
52       Vector_2  PP_0751_1  PP_4191_2        NaN        NaN
53       Vector_2  PP_0751_1  PP_0812_2        NaN        NaN
54       Vector_2  PP_0751_1  PP_1317_2        NaN        NaN
55       Vector_2  PP_0751_1  PP_1506_2        NaN        NaN
56       Vector_2  PP_0751_1  PP_1769_2        NaN        NaN
57       Vector_2  PP_0751_1  PP_2136_2        NaN        NaN
58       Vector_2  PP_0751_1  PP_4120_2        NaN        NaN
59       Vector_2  PP_1317_1  PP_4191_2        NaN        NaN

In [5]:
# Assign the result to all_dispense
df.loc[:, ['number_of_grna', 'gRNA_1', 'gRNA_2', 'gRNA_3', 'gRNA_4']] = temp_df[['number_of_grna', 'gRNA_1', 'gRNA_2', 'gRNA_3', 'gRNA_4']]
df.head(10)

  number_of_grna     gRNA_1     gRNA_2     gRNA_3     gRNA_4
0       Vector_4  PP_0368_1  PP_0812_2  PP_0815_3  PP_2136_4
1       Vector_4  PP_0368_1  PP_0751_2  PP_0812_3  PP_0815_4
2       Vector_4  PP_0751_1  PP_0812_2  PP_0813_3  PP_0815_4
3       Vector_4  PP_0368_1  PP_0812_2  PP_0813_3  PP_0815_4
4       Vector_4  PP_0368_1  PP_0812_2  PP_0815_3  PP_1769_4
5       Vector_3  PP_0751_1  PP_0814_2  PP_4189_3        NaN
6       Vector_3  PP_0751_1  PP_0812_2  PP_0813_3        NaN
7       Vector_3  PP_0751_1  PP_0812_2  PP_0815_3        NaN
8       Vector_3  PP_0368_1  PP_0528_2  PP_0812_3        NaN
9       Vector_3  PP_0751_1  PP_0813_2  PP_0815_3        NaN

Reindex the DataFrame and then use a dictionary to map to a 384 well, assuming those are the wells we want to use (A1..)

In [6]:
#384-well plate Dictionary
well_count = {'Value': range(1, 385)}
df384 = pd.DataFrame(well_count)

# Dictionary for a 384-well plate
rows = list(string.ascii_uppercase[:16])  # 'A' to 'P'
wells = [f"{row}{col}" for row in rows for col in range(1, 25)]
df384_translate = {i: wells[i-1] for i in range(1, 385)}

In [7]:
# Remapping source plate for ECHO
df.index = range(1, len(df) + 1)
df['Well'] = df.index.map(df384_translate)
new_order=['Well', 'number_of_grna','gRNA_1','gRNA_2','gRNA_3','gRNA_4']
df=df[new_order]
df.head()

  Well number_of_grna     gRNA_1     gRNA_2     gRNA_3     gRNA_4
1   A1       Vector_4  PP_0368_1  PP_0812_2  PP_0815_3  PP_2136_4
2   A2       Vector_4  PP_0368_1  PP_0751_2  PP_0812_3  PP_0815_4
3   A3       Vector_4  PP_0751_1  PP_0812_2  PP_0813_3  PP_0815_4
4   A4       Vector_4  PP_0368_1  PP_0812_2  PP_0813_3  PP_0815_4
5   A5       Vector_4  PP_0368_1  PP_0812_2  PP_0815_3  PP_1769_4

* Assuming that we are using a maximum of 4 gRNAs + 1 vector, we will have a reaction size of 6.0 uL
* The reaction table will be as follows:
* Assume the following reaction:

| Reagent | Volume (uL) |
|:---|:---|
| gRNAs | 1.0 |
| Vector | 1.0 |
| Cutsmart buffer | 0.5 |
| Water | 4.5 - count(gRNAs) |

Add columns for water_values and buffer_values

In [8]:
def calculate_water_val(grna):
    # Extract the numeric part from the string
    value = int(grna.split('_')[-1])
    # Perform the calculation
    return 4.5 - value

# Apply the function to the 'number_of_grna' column and create a new column 'Water_val'
df['water_volume'] = df['number_of_grna'].apply(calculate_water_val)
df['buffer_volume'] = 0.5
df

,Well,number_of_grna,gRNA_1,gRNA_2,gRNA_3,gRNA_4,water_volume,buffer_volume
1,A1,Vector_4,PP_0368_1,PP_0812_2,PP_0815_3,PP_2136_4,0.5,0.5
2,A2,Vector_4,PP_0368_1,PP_0751_2,PP_0812_3,PP_0815_4,0.5,0.5
3,A3,Vector_4,PP_0751_1,PP_0812_2,PP_0813_3,PP_0815_4,0.5,0.5
4,A4,Vector_4,PP_0368_1,PP_0812_2,PP_0813_3,PP_0815_4,0.5,0.5
5,A5,Vector_4,PP_0368_1,PP_0812_2,PP_0815_3,PP_1769_4,0.5,0.5
6,A6,Vector_3,PP_0751_1,PP_0814_2,PP_4189_3,NaN,1.5,0.5
7,A7,Vector_3,PP_0751_1,PP_0812_2,PP_0813_3,NaN,1.5,0.5
8,A8,Vector_3,PP_0751_1,PP_0812_2,PP_0815_3,NaN,1.5,0.5
9,A9,Vector_3,PP_0368_1,PP_0528_2,PP_0812_3,NaN,1.5,0.5
10,A10,Vector_3,PP_0751_1,PP_0813_2,PP_0815_3,NaN,1.5,0.5
11,A11,Vector_3,PP_0751_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5
12,A12,Vector_3,PP_0751_1,PP_0812_2,PP_4189_3,NaN,1.5,0.5
13,A13,Vector_3,PP_0751_1,PP_0815_2,PP_4189_3,NaN,1.5,0.5
14,A14,Vector_3,PP_0814_1,PP_0815_2,PP_1506_3,NaN,1.5,0.5
15,A15,Vector_3,PP_0812_1,PP_0815_2,PP_4189_3,NaN,1.5,0.5
16,A16,Vector_3,PP_0812_1,PP_0815_2,PP_2136_3,NaN,1.5,0.5
17,A17,Vector_3,PP_0812_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5
18,A18,Vector_3,PP_0812_1,PP_0813_2,PP_4189_3,NaN,1.5,0.5
19,A19,Vector_3,PP_0812_1,PP_0813_2,PP_1317_3,NaN,1.5,0.5
20,A20,Vector_3,PP_0813_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5
21,A21,Vector_3,PP_0814_1,PP_0815_2,PP_1769_3,NaN,1.5,0.5
22,A22,Vector_3,PP_0368_1,PP_0813_2,PP_0815_3,NaN,1.5,0.5
23,A23,Vector_3,PP_0814_1,PP_0815_2,PP_2136_3,NaN,1.5,0.5
24,A24,Vector_3,PP_0368_1,PP_0751_2,PP_0812_3,NaN,1.5,0.5
25,B1,Vector_3,PP_0368_1,PP_0751_2,PP_0813_3,NaN,1.5,0.5
26,B2,Vector_3,PP_0368_1,PP_0751_2,PP_0815_3,NaN,1.5,0.5
27,B3,Vector_3,PP_0368_1,PP_0751_2,PP_4189_3,NaN,1.5,0.5
28,B4,Vector_3,PP_0368_1,PP_0812_2,PP_0814_3,NaN,1.5,0.5
29,B5,Vector_3,PP_0368_1,PP_0812_2,PP_1317_3,NaN,1.5,0.5
30,B6,Vector_3,PP_0368_1,PP_0812_2,PP_2136_3,NaN,1.5,0.5
31,B7,Vector_3,PP_0368_1,PP_0812_2,PP_4189_3,NaN,1.5,0.5
32,B8,Vector_3,PP_0812_1,PP_0813_2,PP_0814_3,NaN,1.5,0.5
33,B9,Vector_3,PP_0368_1,PP_0813_2,PP_4189_3,NaN,1.5,0.5
34,B10,Vector_3,PP_0368_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5
35,B11,Vector_3,PP_0368_1,PP_0815_2,PP_4189_3,NaN,1.5,0.5
36,B12,Vector_2,PP_0812_1,PP_2136_2,NaN,NaN,2.5,0.5
37,B13,Vector_2,PP_0815_1,PP_4191_2,NaN,NaN,2.5,0.5
38,B14,Vector_2,PP_0812_1,PP_4191_2,NaN,NaN,2.5,0.5
39,B15,Vector_2,PP_0815_1,PP_2136_2,NaN,NaN,2.5,0.5
40,B16,Vector_2,PP_0813_1,PP_1317_2,NaN,NaN,2.5,0.5
41,B17,Vector_2,PP_0813_1,PP_2136_2,NaN,NaN,2.5,0.5
42,B18,Vector_2,PP_0812_1,PP_0813_2,NaN,NaN,2.5,0.5
43,B19,Vector_2,PP_0368_1,PP_0437_2,NaN,NaN,2.5,0.5
44,B20,Vector_2,PP_0751_1,PP_4192_2,NaN,NaN,2.5,0.5
45,B21,Vector_2,PP_0528_1,PP_0813_2,NaN,NaN,2.5,0.5
46,B22,Vector_2,PP_0437_1,PP_0751_2,NaN,NaN,2.5,0.5
47,B23,Vector_2,PP_0437_1,PP_0812_2,NaN,NaN,2.5,0.5
48,B24,Vector_2,PP_0437_1,PP_0813_2,NaN,NaN,2.5,0.5
49,C1,Vector_2,PP_0437_1,PP_0815_2,NaN,NaN,2.5,0.5
50,C2,Vector_2,PP_0528_1,PP_0751_2,NaN,NaN,2.5,0.5
51,C3,Vector_2,PP_0528_1,PP_0812_2,NaN,NaN,2.5,0.5
52,C4,Vector_2,PP_0528_1,PP_1317_2,NaN,NaN,2.5,0.5
53,C5,Vector_2,PP_0751_1,PP_4191_2,NaN,NaN,2.5,0.5
54,C6,Vector_2,PP_0751_1,PP_0812_2,NaN,NaN,2.5,0.5
55,C7,Vector_2,PP_0751_1,PP_1317_2,NaN,NaN,2.5,0.5
56,C8,Vector_2,PP_0751_1,PP_1506_2,NaN,NaN,2.5,0.5
57,C9,Vector_2,PP_0751_1,PP_1769_2,NaN,NaN,2.5,0.5
58,C10,Vector_2,PP_0751_1,PP_2136_2,NaN,NaN,2.5,0.5
59,C11,Vector_2,PP_0751_1,PP_4120_2,NaN,NaN,2.5,0.5
60,C12,Vector_2,PP_1317_1,PP_4191_2,NaN,NaN,2.5,0.5

In [9]:
# Function to extract the gRNA type and return it
def extract_grna_type(grna):
    # Extract the numeric part from the string
    return int(grna.split('_')[-1])

df['gRNA_type'] = df['number_of_grna'].apply(extract_grna_type)

# Group by the gRNA type and count the occurrences
gRNA_counts = df['gRNA_type'].value_counts().sort_index()

In [10]:
# Ensure the 'Count', 'plasmid', and 'water' columns are numeric, coerce errors to NaN
df_temp=df
df_temp.loc[:,'water_volume'] = pd.to_numeric(df['water_volume'], errors='coerce')
df_temp.loc[:,'buffer_volume'] = pd.to_numeric(df['buffer_volume'], errors='coerce')
sum_buffer = (df_temp['buffer_volume']).sum()
sum_water = (df_temp['water_volume']).sum()
maximum_plasmid=gRNA_counts.max()

# Print the results
print(f"Maximum plasmid volume is {maximum_plasmid}")
print(f"Total water dispense is: {sum_water}")
print(f"Total buffer dispense is: {sum_buffer}")

Maximum plasmid volume is 30
Total water dispense is: 110.0
Total buffer dispense is: 30.0

### Import the assembly dispense list
* The destination plate from the ligation and digestion is purified and then it becomes the dispense plate for the electroporations

In [11]:
ECHO_Source=pd.read_csv(os.path.join(dispense_path,f'{timestamp}_ECHO_Assembly_Source_Map_DBTL{cycle}.csv'))

ECHO_Source=ECHO_Source[['gRNA_Target']]
ECHO_Source.head()

  gRNA_Target
0   PP_0368_1
1   PP_0751_1
2   PP_0812_1
3   PP_0528_1
4   PP_0437_1

In [12]:
sum_water=sum_water.round(0)
sum_buffer=sum_buffer.round(0)

water_aliquot=65
working_vol=water_aliquot-20

water_wells = np.ceil(sum_water/working_vol)
buffer_wells=np.ceil(sum_buffer/working_vol)

buffer_rows_list=[]
water_rows_list=[]

for i in range(int(water_wells)):
    water_row = {f"Water_{i+1}"}
    water_rows_list.append(water_row)
    
for i in range(int(buffer_wells)):
    buffer_row = {f"Buffer_{i+1}"}
    buffer_rows_list.append(buffer_row)
    
water_df=pd.DataFrame(water_rows_list,columns=ECHO_Source.columns)
buffer_df=pd.DataFrame(buffer_rows_list,columns=ECHO_Source.columns)

temp_df=ECHO_Source.copy()
temp_df=pd.concat([ECHO_Source, water_df,buffer_df], ignore_index=True)

ECHO_Source=temp_df[['gRNA_Target']]
ECHO_Source.tail()

   gRNA_Target
37    Vector_4
38     Water_1
39     Water_2
40     Water_3
41    Buffer_1

In [13]:
ECHO_Source.index = range(1, len(ECHO_Source) + 1)
ECHO_Source['Well'] = ECHO_Source.index.map(df384_translate)
new_order=['Well', 'gRNA_Target']
ECHO_Source=ECHO_Source[new_order]
ECHO_Source

   Well gRNA_Target
1    A1   PP_0368_1
2    A2   PP_0751_1
3    A3   PP_0812_1
4    A4   PP_0528_1
5    A5   PP_0437_1
6    A6   PP_0814_1
7    A7   PP_0813_1
8    A8   PP_0815_1
9    A9   PP_1317_1
10  A10   PP_0812_2
11  A11   PP_0813_2
12  A12   PP_0815_2
13  A13   PP_0751_2
14  A14   PP_0814_2
15  A15   PP_2136_2
16  A16   PP_4191_2
17  A17   PP_1317_2
18  A18   PP_0528_2
19  A19   PP_0437_2
20  A20   PP_4192_2
21  A21   PP_1506_2
22  A22   PP_1769_2
23  A23   PP_4120_2
24  A24   PP_0815_3
25   B1   PP_4189_3
26   B2   PP_0813_3
27   B3   PP_0812_3
28   B4   PP_2136_3
29   B5   PP_1317_3
30   B6   PP_0814_3
31   B7   PP_1506_3
32   B8   PP_1769_3
33   B9   PP_0815_4
34  B10   PP_2136_4
35  B11   PP_1769_4
36  B12    Vector_2
37  B13    Vector_3
38  B14    Vector_4
39  B15     Water_1
40  B16     Water_2
41  B17     Water_3
42  B18    Buffer_1

In [14]:
# Initialize variables
running_sum = 0

water_counter = 1
buffer_counter = 1

water_list = []
buffer_list =[] 

# Loop through the DataFrame and assign wells
for value in df['water_volume']:
    running_sum += value
    if running_sum > 40:
        water_counter += 1
        running_sum = value  # start new well with current value
    water_list.append(f'Water_{water_counter}')

df['water_source'] = water_list
running_sum = 0

# Loop through the DataFrame and assign wells
for value2 in df['buffer_volume']:
    running_sum += value2
    if running_sum > 40:
        buffer_counter += 1
        running_sum = value2  # start new well with current value
    buffer_list.append(f'Buffer_{buffer_counter}')

df['buffer_source'] = buffer_list
df

,Well,number_of_grna,gRNA_1,gRNA_2,gRNA_3,gRNA_4,water_volume,buffer_volume,gRNA_type,water_source,buffer_source
1,A1,Vector_4,PP_0368_1,PP_0812_2,PP_0815_3,PP_2136_4,0.5,0.5,4,Water_1,Buffer_1
2,A2,Vector_4,PP_0368_1,PP_0751_2,PP_0812_3,PP_0815_4,0.5,0.5,4,Water_1,Buffer_1
3,A3,Vector_4,PP_0751_1,PP_0812_2,PP_0813_3,PP_0815_4,0.5,0.5,4,Water_1,Buffer_1
4,A4,Vector_4,PP_0368_1,PP_0812_2,PP_0813_3,PP_0815_4,0.5,0.5,4,Water_1,Buffer_1
5,A5,Vector_4,PP_0368_1,PP_0812_2,PP_0815_3,PP_1769_4,0.5,0.5,4,Water_1,Buffer_1
6,A6,Vector_3,PP_0751_1,PP_0814_2,PP_4189_3,NaN,1.5,0.5,3,Water_1,Buffer_1
7,A7,Vector_3,PP_0751_1,PP_0812_2,PP_0813_3,NaN,1.5,0.5,3,Water_1,Buffer_1
8,A8,Vector_3,PP_0751_1,PP_0812_2,PP_0815_3,NaN,1.5,0.5,3,Water_1,Buffer_1
9,A9,Vector_3,PP_0368_1,PP_0528_2,PP_0812_3,NaN,1.5,0.5,3,Water_1,Buffer_1
10,A10,Vector_3,PP_0751_1,PP_0813_2,PP_0815_3,NaN,1.5,0.5,3,Water_1,Buffer_1
11,A11,Vector_3,PP_0751_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5,3,Water_1,Buffer_1
12,A12,Vector_3,PP_0751_1,PP_0812_2,PP_4189_3,NaN,1.5,0.5,3,Water_1,Buffer_1
13,A13,Vector_3,PP_0751_1,PP_0815_2,PP_4189_3,NaN,1.5,0.5,3,Water_1,Buffer_1
14,A14,Vector_3,PP_0814_1,PP_0815_2,PP_1506_3,NaN,1.5,0.5,3,Water_1,Buffer_1
15,A15,Vector_3,PP_0812_1,PP_0815_2,PP_4189_3,NaN,1.5,0.5,3,Water_1,Buffer_1
16,A16,Vector_3,PP_0812_1,PP_0815_2,PP_2136_3,NaN,1.5,0.5,3,Water_1,Buffer_1
17,A17,Vector_3,PP_0812_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5,3,Water_1,Buffer_1
18,A18,Vector_3,PP_0812_1,PP_0813_2,PP_4189_3,NaN,1.5,0.5,3,Water_1,Buffer_1
19,A19,Vector_3,PP_0812_1,PP_0813_2,PP_1317_3,NaN,1.5,0.5,3,Water_1,Buffer_1
20,A20,Vector_3,PP_0813_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5,3,Water_1,Buffer_1
21,A21,Vector_3,PP_0814_1,PP_0815_2,PP_1769_3,NaN,1.5,0.5,3,Water_1,Buffer_1
22,A22,Vector_3,PP_0368_1,PP_0813_2,PP_0815_3,NaN,1.5,0.5,3,Water_1,Buffer_1
23,A23,Vector_3,PP_0814_1,PP_0815_2,PP_2136_3,NaN,1.5,0.5,3,Water_1,Buffer_1
24,A24,Vector_3,PP_0368_1,PP_0751_2,PP_0812_3,NaN,1.5,0.5,3,Water_1,Buffer_1
25,B1,Vector_3,PP_0368_1,PP_0751_2,PP_0813_3,NaN,1.5,0.5,3,Water_1,Buffer_1
26,B2,Vector_3,PP_0368_1,PP_0751_2,PP_0815_3,NaN,1.5,0.5,3,Water_1,Buffer_1
27,B3,Vector_3,PP_0368_1,PP_0751_2,PP_4189_3,NaN,1.5,0.5,3,Water_1,Buffer_1
28,B4,Vector_3,PP_0368_1,PP_0812_2,PP_0814_3,NaN,1.5,0.5,3,Water_1,Buffer_1
29,B5,Vector_3,PP_0368_1,PP_0812_2,PP_1317_3,NaN,1.5,0.5,3,Water_1,Buffer_1
30,B6,Vector_3,PP_0368_1,PP_0812_2,PP_2136_3,NaN,1.5,0.5,3,Water_1,Buffer_1
31,B7,Vector_3,PP_0368_1,PP_0812_2,PP_4189_3,NaN,1.5,0.5,3,Water_2,Buffer_1
32,B8,Vector_3,PP_0812_1,PP_0813_2,PP_0814_3,NaN,1.5,0.5,3,Water_2,Buffer_1
33,B9,Vector_3,PP_0368_1,PP_0813_2,PP_4189_3,NaN,1.5,0.5,3,Water_2,Buffer_1
34,B10,Vector_3,PP_0368_1,PP_0814_2,PP_0815_3,NaN,1.5,0.5,3,Water_2,Buffer_1
35,B11,Vector_3,PP_0368_1,PP_0815_2,PP_4189_3,NaN,1.5,0.5,3,Water_2,Buffer_1
36,B12,Vector_2,PP_0812_1,PP_2136_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
37,B13,Vector_2,PP_0815_1,PP_4191_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
38,B14,Vector_2,PP_0812_1,PP_4191_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
39,B15,Vector_2,PP_0815_1,PP_2136_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
40,B16,Vector_2,PP_0813_1,PP_1317_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
41,B17,Vector_2,PP_0813_1,PP_2136_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
42,B18,Vector_2,PP_0812_1,PP_0813_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
43,B19,Vector_2,PP_0368_1,PP_0437_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
44,B20,Vector_2,PP_0751_1,PP_4192_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
45,B21,Vector_2,PP_0528_1,PP_0813_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
46,B22,Vector_2,PP_0437_1,PP_0751_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
47,B23,Vector_2,PP_0437_1,PP_0812_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
48,B24,Vector_2,PP_0437_1,PP_0813_2,NaN,NaN,2.5,0.5,2,Water_2,Buffer_1
49,C1,Vector_2,PP_0437_1,PP_0815_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
50,C2,Vector_2,PP_0528_1,PP_0751_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
51,C3,Vector_2,PP_0528_1,PP_0812_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
52,C4,Vector_2,PP_0528_1,PP_1317_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
53,C5,Vector_2,PP_0751_1,PP_4191_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
54,C6,Vector_2,PP_0751_1,PP_0812_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
55,C7,Vector_2,PP_0751_1,PP_1317_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
56,C8,Vector_2,PP_0751_1,PP_1506_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
57,C9,Vector_2,PP_0751_1,PP_1769_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
58,C10,Vector_2,PP_0751_1,PP_2136_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
59,C11,Vector_2,PP_0751_1,PP_4120_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1
60,C12,Vector_2,PP_1317_1,PP_4191_2,NaN,NaN,2.5,0.5,2,Water_3,Buffer_1

In [15]:
dispense_dict = ECHO_Source.set_index('gRNA_Target')['Well'].to_dict()

In [16]:
# Replace the prefix, suffix, and gRNA_Target in the source DataFrame using the dictionary
for column in df.columns:
    df[column] = df[column].map(dispense_dict).fillna(df[column])

df.head()

,Well,number_of_grna,gRNA_1,gRNA_2,gRNA_3,gRNA_4,water_volume,buffer_volume,gRNA_type,water_source,buffer_source
1,A1,B14,A1,A10,A24,B10,0.5,0.5,4,B15,B18
2,A2,B14,A1,A13,B3,B9,0.5,0.5,4,B15,B18
3,A3,B14,A2,A10,B2,B9,0.5,0.5,4,B15,B18
4,A4,B14,A1,A10,B2,B9,0.5,0.5,4,B15,B18
5,A5,B14,A1,A10,A24,B11,0.5,0.5,4,B15,B18

In [17]:
df = df.rename(columns={'Well': 'Destination Well'})
df.head()

,Destination Well,number_of_grna,gRNA_1,gRNA_2,gRNA_3,gRNA_4,water_volume,buffer_volume,gRNA_type,water_source,buffer_source
1,A1,B14,A1,A10,A24,B10,0.5,0.5,4,B15,B18
2,A2,B14,A1,A13,B3,B9,0.5,0.5,4,B15,B18
3,A3,B14,A2,A10,B2,B9,0.5,0.5,4,B15,B18
4,A4,B14,A1,A10,B2,B9,0.5,0.5,4,B15,B18
5,A5,B14,A1,A10,A24,B11,0.5,0.5,4,B15,B18

#### Consolidate individual dispenses
* We want a three column output with Source Well, volume, and destination well

| Sample Group | Source Plate Type | Source Well | Source Plate Name | Destination Plate Name | Destination Well | Transfer Volume |
|--------------|-------------------|-------------|-------------------|------------------------|------------------|-----------------|
| AQ           | 384PP_AQ_SP2      | A1          | Parts_Library_1   | Digest_and_Ligate      | A1               | 2000            |
| AQ           | 384PP_AQ_SP2      | A2          | Parts_Library_1   | Digest_and_Ligate      | A2               | 2000            |

In [18]:
gRNA_suffixes = ['1','2','3','4']
gRNA_dfs=[]
for suffix in gRNA_suffixes:
    #Rename the gRNA_suffix column to the Source Well
    gRNA_dfs.append(df[['Destination Well', f'gRNA_{suffix}']].rename(columns={f'gRNA_{suffix}': 'Source Well'}))

vectors = ['Destination Well','number_of_grna']
vectors_df=df[vectors].rename(columns={'number_of_grna':'Source Well'})

#appending the vectors to the gRNAs
gRNA_dfs.append(vectors_df)

In [19]:
# Concatenate all DataFrames in the list
gRNAs_df = pd.concat(gRNA_dfs, axis=0, ignore_index=True)
gRNAs_df_filtered = gRNAs_df[gRNAs_df['Source Well'].notna()]

#Setting all volumes to be 1 for each positional guide arrangement
gRNAs_slice_df=gRNAs_df_filtered.copy()
gRNAs_slice_df.loc[:, 'Transfer Volume']=1
gRNAs_slice_df

    Destination Well Source Well  Transfer Volume
0                 A1          A1                1
1                 A2          A1                1
2                 A3          A2                1
3                 A4          A1                1
4                 A5          A1                1
..               ...         ...              ...
295               C8         B12                1
296               C9         B12                1
297              C10         B12                1
298              C11         B12                1
299              C12         B12                1

[220 rows x 3 columns]

In [20]:
other=['buffer_source','buffer_volume','Destination Well']
water=['water_source','water_volume','Destination Well']

# Extracting columns and creating DataFrames
other_df = pd.DataFrame(df[other])
other_df = other_df.rename(columns={'buffer_source': 'Source Well'})
other_df = other_df.rename(columns={'buffer_volume':'Transfer Volume'})

water_df = pd.DataFrame(df[water])
water_df = water_df.rename(columns={'water_source': 'Source Well'})
water_df = water_df.rename(columns={'water_volume':'Transfer Volume'})         

# Concatenate the data frames so that everything is on the same list
CRISPRi_Assemblies = []
CRISPRi_Assemblies = pd.concat([gRNAs_slice_df, water_df, other_df], axis=0)
CRISPRi_Assemblies

   Destination Well Source Well  Transfer Volume
0                A1          A1              1.0
1                A2          A1              1.0
2                A3          A2              1.0
3                A4          A1              1.0
4                A5          A1              1.0
..              ...         ...              ...
56               C8         B18              0.5
57               C9         B18              0.5
58              C10         B18              0.5
59              C11         B18              0.5
60              C12         B18              0.5

[340 rows x 3 columns]

In [21]:
ECHO_columns = {
    "Sample Group": "AQ",
    "Source Plate Name": f"Parts_Library_DBTL{cycle}",
    "Destination Plate Name": f"CRISPRi_Assemblies_DBTL{cycle}",
    "Source Plate Type": "384PP_AQ_SP2"
}

# Add new columns to DataFrame
CRISPRi_Assemblies = CRISPRi_Assemblies.assign(**ECHO_columns)
CRISPRi_Assemblies.head(1)

,Destination Well,Source Well,Transfer Volume,Sample Group,Source Plate Name,Destination Plate Name,Source Plate Type
0,A1,A1,1.0,AQ,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,384PP_AQ_SP2

In [22]:
#Reorganize the DataFrame headers
columns_order = [3, 6, 1, 4, 5, 0, 2]  # Ordering according to the ECHO
CRISPRi_Assemblies = CRISPRi_Assemblies[CRISPRi_Assemblies.columns[columns_order]]
CRISPRi_Assemblies['Transfer Volume'] = CRISPRi_Assemblies['Transfer Volume'].multiply(1000).round()
CRISPRi_Assemblies

,Sample Group,Source Plate Type,Source Well,Source Plate Name,Destination Plate Name,Destination Well,Transfer Volume
0,AQ,384PP_AQ_SP2,A1,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,A1,1000.0
1,AQ,384PP_AQ_SP2,A1,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,A2,1000.0
2,AQ,384PP_AQ_SP2,A2,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,A3,1000.0
3,AQ,384PP_AQ_SP2,A1,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,A4,1000.0
4,AQ,384PP_AQ_SP2,A1,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,A5,1000.0
...,...,...,...,...,...,...,...
56,AQ,384PP_AQ_SP2,B18,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,C8,500.0
57,AQ,384PP_AQ_SP2,B18,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,C9,500.0
58,AQ,384PP_AQ_SP2,B18,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,C10,500.0
59,AQ,384PP_AQ_SP2,B18,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,C11,500.0
60,AQ,384PP_AQ_SP2,B18,Parts_Library_DBTL5,CRISPRi_Assemblies_DBTL5,C12,500.0

### Save the file under Dispense_Files

In [23]:
CRISPRi_Assemblies = CRISPRi_Assemblies.sort_values('Destination Well',ascending=(True))

CRISPRi_Assemblies.to_csv(os.path.join(dispense_path, f'{timestamp}_ECHO_Assembly_Dispense_DBTL{cycle}.csv'), index=False)